version: '3.9'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    ports:
      # cypas-local-tls-proxyとportが被るためずらしている
      - 8004:8004

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile.prod
    container_name: redis
    volumes:
      - redis_data:/data

  express:
    build:
      dockerfile: express/Dockerfile.prod
    container_name: express
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8001:8001

volumes:
  redis_data:
