version: '3.9'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: nginx
    ports:
      # cypas-local-tls-proxyとportが被るためずらしている
      - 8004:8004

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile.dev
    container_name: redis
    volumes:
      - redis_data:/data

  express:
    build:
      context: ./express
      dockerfile: Dockerfile.dev
    container_name: express
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./express:/usr/src/app
      - ./.env:/usr/src/app/.env
      - express_node_modules:/usr/src/app/node_modules
      - .vscode:/usr/src/app/.vscode
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8001:8001
volumes:
  express_node_modules:
  redis_data:
