version: '3'
services:
  user-agent-wetty-UNIQUE:
    build:
      context: ./wetty
    image: user-agent-wetty
    container_name: user-agent-wetty-${USER_AGENT_NAME}
    entrypoint: yarn start --ssh-host user-agent-kali-UNIQUE --ssh-user ${USER_AGENT_NAME} --ssh-pass ${USER_AGENT_PASSWORD}  --base / --allow-iframe true
    ports:
      - ${USER_AGENT_PORT}:3000

  user-agent-kali-UNIQUE:
    build:
      context: ./kali
    tty: true
    image: user-agent-kali
    container_name: user-agent-kali-${USER_AGENT_NAME}
    # ユーザーを作成してssh server起動
    command: >
      bash -c "
      useradd -m ${USER_AGENT_NAME} &&
      echo '${USER_AGENT_NAME}:${USER_AGENT_PASSWORD}' | chpasswd &&
      usermod -aG sudo ${USER_AGENT_NAME} &&
      chsh -s /bin/bash ${USER_AGENT_NAME} &&
      service ssh start &&
      /bin/bash
      "
